[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spotify_dapp = "9JZVRWwQntJVwk1t5mDHkggtHoNW8NkpFtAVqCiorY4Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/johnivanpuayap/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
